# Generated by Django 2.1.7 on 2019-04-30 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='trigger',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Key'),
        ),
    ]
