# Generated by Django 2.1.7 on 2019-05-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190430_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Key'),
        ),
    ]
