# Generated by Django 2.1.7 on 2019-05-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190506_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trigger_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventdefinition',
            name='retriggerable',
            field=models.BooleanField(default=False),
        ),
    ]
