# Generated by Django 2.1.7 on 2019-05-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190506_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='trigger_flag',
            new_name='triggered',
        ),
    ]
