# Generated by Django 2.1.7 on 2019-05-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190506_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='triggered',
            field=models.BooleanField(default=True),
        ),
    ]
