# Generated by Django 2.1.7 on 2019-04-22 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=64)),
                ('owner', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=128)),
                ('hostname', models.CharField(max_length=63)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('state', models.CharField(choices=[('protected', 'Load Protected'), ('battery', 'On Battery'), ('bypass', 'On Bypass'), ('commloss', 'Communication Loss')], default='commloss', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('UPS', 'UPS'), ('PDU', 'PDU'), ('VMG', 'Virtual Machine Guest'), ('VMH', 'Virtual Machine Host')], max_length=3)),
                ('manufacturer', models.CharField(max_length=64)),
                ('product_line', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Group'),
        ),
        migrations.AddField(
            model_name='device',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Product'),
        ),
    ]
