# Generated by Django 2.1.7 on 2019-07-03 15:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20190422_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connector', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='connector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Connector'),
        ),
    ]
