# Generated by Django 2.1.7 on 2019-04-23 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0006_periodictask_priority'),
        ('devices', '0003_auto_20190422_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmomiConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('port', models.IntegerField(default=443, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('user', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('session_key', models.CharField(max_length=64)),
                ('max_polls', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Group')),
                ('periodic_task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask')),
            ],
        ),
    ]
