# Generated by Django 2.1.7 on 2019-04-23 17:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vmomi', '0002_auto_20190423_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('endpoint', models.CharField(max_length=128)),
                ('vmomi_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmomi.VmomiConfig')),
            ],
        ),
    ]
