# Generated by Django 2.1.7 on 2019-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmomi', '0003_endpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='endpoint',
            new_name='attribute',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='vim_type',
            field=models.CharField(default='vim.VirtualMachine', max_length=128),
            preserve_default=False,
        ),
    ]
