# Generated by Django 2.1.7 on 2019-04-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmomi', '0004_auto_20190423_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='vim_type',
            field=models.CharField(choices=[('Datacenter', 'vim.Datacenter'), ('ClusterComputeResource', 'vim.ClusterComputeResource'), ('HostSystem', 'vim.HostSystem'), ('VirtualMachine', 'vim.VirtualMachine'), ('Datastore', 'vim.Datastore'), ('ResourcePool', 'vim.ResourcePool'), ('Folder', 'vim.Folder'), ('Network', 'vim.Network')], max_length=22),
        ),
    ]
