# Generated by Django 2.1.7 on 2019-04-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmomi', '0005_auto_20190425_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='vim_type',
            field=models.CharField(choices=[('Datacenter', 'Datacenter'), ('ClusterComputeResource', 'ClusterComputeResource'), ('HostSystem', 'HostSystem'), ('VirtualMachine', 'VirtualMachine'), ('Datastore', 'Datastore'), ('ResourcePool', 'ResourcePool'), ('Folder', 'Folder'), ('Network', 'Network')], max_length=22),
        ),
    ]
