# Generated by Django 2.1.7 on 2019-05-06 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmomi', '0007_auto_20190504_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Key'),
        ),
    ]
