# Generated by Django 2.1.7 on 2019-04-23 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolconfig',
            name='max_polls',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
