# Generated by Django 2.1.7 on 2019-04-23 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp', '0002_protocolconfig_max_polls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolconfig',
            name='max_polls',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
