# Generated by Django 2.1.7 on 2019-05-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190430_1632'),
        ('snmp', '0003_auto_20190423_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolconfig',
            old_name='group',
            new_name='device_group',
        ),
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Key'),
        ),
    ]
