# Generated by Django 2.1.7 on 2019-05-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20190422_2019'),
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='device_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Group'),
        ),
    ]
