# Generated by Django 2.1.7 on 2019-05-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_automation_device_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automation',
            old_name='device_group',
            new_name='target_group',
        ),
    ]
