# Generated by Django 2.1.7 on 2019-05-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_auto_20190503_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='next',
            field=models.ManyToManyField(null=True, related_name='_automation_next_+', to='automations.Automation'),
        ),
    ]
