# Generated by Django 2.1.7 on 2019-05-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0005_automation_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='next',
            field=models.ManyToManyField(related_name='_automation_next_+', to='automations.Automation'),
        ),
    ]
