# Generated by Django 2.1.7 on 2019-05-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0007_auto_20190509_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventDefinition'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='source_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_group', to='devices.Group'),
        ),
    ]
