# Generated by Django 2.1.7 on 2019-05-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0008_auto_20190509_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='next',
            field=models.ManyToManyField(blank=True, to='automations.Automation'),
        ),
    ]
