# Generated by Django 2.1.7 on 2019-05-09 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0009_auto_20190509_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='next',
        ),
        migrations.AddField(
            model_name='automation',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automations.Automation'),
        ),
    ]
